### ISSUE TITLE
it is written that Java code is existing some were , can you share where is it?

### ISSUE THREAD

**Issue by Sandy4321** [NeerajSarwan/CPT#2]
it is written

in
A Guide to Sequence Prediction using Compact Prediction Tree (with codes in Python)
 that Java code is existing some were , can you share where is it?
https://www.analyticsvidhya.com/blog/2018/04/guide-sequence-prediction-using-compact-prediction-tree-python/?utm_source=feedburner&utm_medium=email&utm_campaign=Feed%3A+AnalyticsVidhya+%28Analytics+Vidhya%29

**Comment by mdalvi** [comment]
@Sandy4321 I believe this should be useful, [SPMF: A Java Open-Source Data Mining Library](http://www.philippe-fournier-viger.com/spmf/index.php?link=algorithms.php) . It does have CPT code.

**Comment by NeerajSarwan** [comment]
mdalvi pointed to the right link. Closing the issue.
